# Generated by Django 5.0 on 2024-04-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('image', models.FileField(default='', upload_to='media/')),
                ('price', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0, max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100)),
            ],
        ),
    ]
