# Generated by Django 5.0 on 2024-04-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
