# Generated by Django 4.2.5 on 2024-04-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_myprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myprofile',
            old_name='fname',
            new_name='name',
        ),
    ]
