# Generated by Django 4.2.5 on 2024-04-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_cart_userid'),
        ('firstapp', '0005_rename_name_myprofile_fname'),
    ]

    operations = [
    ]
