# Generated by Django 4.2.5 on 2024-04-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_merge_20240415_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myprofile',
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='userid',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
