# Generated by Django 4.2.5 on 2024-04-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_delete_myprofile_alter_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='productid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
