# Generated by Django 4.2.5 on 2024-04-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_cart_subtotal_alter_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='subtotal',
        ),
    ]
