# Generated by Django 5.0 on 2024-05-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_remove_cart_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='productreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('review', models.CharField(max_length=100)),
                ('rname', models.CharField(max_length=100)),
                ('remail', models.CharField(max_length=100)),
            ],
        ),
    ]
