# Generated by Django 5.0 on 2024-05-10 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_productreview_productid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productreview',
            new_name='customerreview',
        ),
    ]
