# Generated by Django 5.0 on 2024-03-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='image',
            field=models.FileField(default='', upload_to='media/'),
        ),
    ]
