# Generated by Django 4.2.5 on 2024-03-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_productdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='discount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='pstatus',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
    ]
