# Generated by Django 5.0 on 2024-04-03 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_productdata_discount_alter_productdata_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
