# Generated by Django 5.0 on 2024-04-03 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_subcategory_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='status',
            new_name='substatus',
        ),
    ]
