# Generated by Django 5.0 on 2024-05-20 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_contactinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactinfo',
        ),
    ]
