# Generated by Django 5.0 on 2024-05-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_delete_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cemail', models.EmailField(max_length=100)),
                ('cphone', models.CharField(max_length=100)),
                ('cbirthdate', models.CharField(max_length=100)),
                ('cclinic', models.CharField(max_length=100)),
                ('cdoctor', models.CharField(max_length=100)),
                ('cmessage', models.CharField(max_length=100)),
            ],
        ),
    ]
