# Generated by Django 5.0 on 2024-05-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_billing_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_details',
            name='buserid',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
