# Generated by Django 5.0 on 2024-05-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_billing_details_buserid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_details',
            name='buserid',
            field=models.CharField(max_length=100),
        ),
    ]
