# Generated by Django 4.2.5 on 2024-05-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_billing_details_buserid'),
    ]

    operations = [
        migrations.CreateModel(
            name='userorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ouserid', models.IntegerField(default=0)),
                ('oproductid', models.IntegerField(default=0)),
                ('oproduct', models.CharField(max_length=100)),
                ('oimage', models.FileField(default='', upload_to='media/')),
                ('oprice', models.CharField(max_length=100)),
                ('oquantity', models.IntegerField(default=1)),
                ('ototal', models.CharField(max_length=100)),
                ('odiscount', models.CharField(max_length=100)),
            ],
        ),
    ]
